config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users

  post 'projects/send_link_action', to: 'projects#send_link_action'
  post 'projects/project_update_request', to: 'projects#project_update_request'
  resources :projects do
    resources :tasks do
      member do
        get :complete
        get :incomplete
      end
    end
  end

  root "projects#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  def completed?
  	completed_at.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    if user_signed_in?
    @projects = Project.where(:user_id => current_user.id)
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @user_all = User.where.not(:id => current_user.id)
    @notice = 'success'
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def send_link_action
    @message = params
    ActionCable.server.broadcast 'links',
      message: @message
    head :ok
  end

  def project_update_request
    template =  render :partial => 'projects/project_template/title_description', locals: {:project => set_project} 
    ActionCable.server.broadcast 'project',
      message: template,
      user_id: set_project[:user_id],
      project_id: set_project[:id]
    head :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, except: [:create]

  def create
	@task = @project.tasks.new(task_params)
	if @task.save
      template =  render :partial => 'tasks/task', locals: {:project => @task.project, :current_user => current_user, :task => @task} 
      ActionCable.server.broadcast 'tasks',
      project_id: @task.project_id,
      task_content: template,
      user_id: current_user.id
      head :ok
    end
  end

  def destroy
    if @task.destroy
	  flash[:success] = "Task was deleted!"
	else 
	  flash[:error] = "Task was not deleted"
	end
		
	  ActionCable.server.broadcast 'tasksdelete',
      task_id: @task.id
      head :ok
	end

	def complete
	  @task.update_attribute(:completed_at, Time.now)
	  template =  render :partial => 'tasks/task_inner', locals: {:project => @task.project, :current_user => current_user, :task => @task}

	  ActionCable.server.broadcast 'tasksupdate',
      task_id: @task.id,
      template: template,
      user_id: current_user.id
      head :ok
	end

	def incomplete
	  @task.update_attribute(:completed_at, nil)
	  template =  render :partial => 'tasks/task_inner', locals: {:project => @task.project, :current_user => current_user, :task => @task}

	  ActionCable.server.broadcast 'tasksupdate',
      task_id: @task.id,
      template: template,
      user_id: current_user.id
      head :ok
	end


	private

	def set_task
	  @task = @project.tasks.find(params[:id])
	end

	def set_project
	  @project = Project.find(params[:project_id])
	end

	def task_params
	  params[:task].permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectMenagement</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>
  <body>
    <% if current_user.present? %>
      <body data-user="<%= current_user.id %>">
    <% end %>
    <nav class="navbar navbar-default">
      <div class="navbar-header">
        <%= link_to "Lukasz ToDo Application", root_path, class:"navbar-brand" %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <%= link_to "Create Project", new_project_path, class: "navbar-text navbar-link" %>
      <% end %>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      </ul>
    </div>
  <% end %>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :project_title %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :project_description %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_welcome_page.html.erb
<div class="jumbotron">
  <h2> ToDo Application</h2>
  <h4>Lukasz Gebicki</h4>
  <br>
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-danger" %>
  <%= link_to "Log In", new_user_session_path, class: "btn btn-danger" %>
</div>

app/views/projects/edit.html.erb
<h1 class="todo_list_title">Edit Project</h1>
<div class="forms">
  <%= render 'form', project: @project %>
</div>
<div class="links">
  <%= link_to 'Cancel', projects_path %>
</div>

app/views/projects/index.html.erb
<% if user_signed_in? %>
  <div id=”messages”></div>
  <% if (@projects.length > 0) %>
    <% @projects.each do |project| %>
      <div class="index_row clearfix">
        <h2 class="todo_list_title">
          <%= link_to project.title, project %>
        </h2>
        <p class="todo_list_sub_title">
          <%= project.description %>
        </p>
      </div>
    <% end %>
  <% else %>
    <center style='color: #eee;font-size: 33px;text-shadow: 1px 1px 1px #bbb6b6;'>
      There are no projects for you, <%= link_to "create one", new_project_path, class: "project_creat_one_link" %> 
    </center>
  <% end %>
  
<% else %>
    <%= render 'welcome_page' %>
<% end %>

app/views/projects/new.html.erb
<h1 class="todo_list_title">New Project</h1>
<div class="forms">
  <%= render 'form', project: @project %>
</div>
<div class="links">
  <%= link_to 'Back', projects_path %>
</div>

app/views/projects/project_template/_title_description.html.erb
<h2 class="todo_list_title"><%= project.title %></h2>
<p class="todo_list_sub_title"><%= project.description %></p>

app/views/projects/show.html.erb
<div class="project_detail <%= @project.id %>">
<p id="notice"><%= notice %></p>

<% if (notice.present?) %>
    <script type="text/javascript">
      $(document).ready(function() {
          $.ajax({
              url: "/projects/project_update_request",
              type: "POST",
              dataType: "json",
              beforeSend: function(xhr) {xhr.setRequestHeader("X-CSRF-Token", $("meta[name='csrf-token']").attr("content"))},
              data: {"id": <%= @project.id %>},
              success: function(response){
                  console.log(response);
              }
          });
      });
    </script>
<% end %>

<div class="project_description">
  <%= render :partial => 'projects/project_template/title_description', locals: {:project => @project} %>
</div>
<div id="todo_items_wrapper">
  <% if @project.tasks.any? %>
    <div class="panel-body" id="tasks" data-project="<%= @project[:id] %>">
      <%= render partial: 'tasks/task', collection: @project.tasks, locals: {:project => @project}%>
    </div>
  <%else%>
    <div class="panel-body hidden" id="tasks" data-project="<%= @project[:id] %>"></div>
  <%end%>

  <center style='color: #543d2f;font-size: 19px;padding: 10px;' class='no_task_present <% if @project.tasks.any? %> hidden <% end %> '> Your project is empty. Create your first task</center>
  

  <% if (current_user.id == @project.user_id) %>
    <%= render "tasks/form" %>
    <%= form_tag({:action => 'send_link_action', :controller => 'projects'},:class => 'url_area', :remote => true, :method => 'post') do %>
      <input type="text" class="url_link form-control" name="url_link" disabled />
      <input type="hidden" class="form-control" name="project_id" value="<%= @project[:id] %>"  />
      <%= select_tag 'user', options_for_select(@user_all.collect{ |user| [user.email, user.id]}),  :class => 'form-control select_user' %>
      <button type="button" class="btn btn-make-link">share this project</button>
      <button type="submit" class="btn btn-send-link" style="display: none">Send</button>
      <button type="button" class="btn btn-cancel-link" style="display: none">cancel</button>
    <% end %>
  <% end %>
</div>
<% if (current_user.id == @project.user_id) %>
  <div class="links">
    <%= link_to 'Edit', edit_project_path(@project) %> |
    <%= link_to 'Back', projects_path %> |
    <%= link_to 'Delete', project_path(@project), method: :delete, data: {confirm: "Are you sure?"} %>
  </div>
<% end %>
</div>

app/views/tasks/_form.html.erb
<%= form_for([@project, @project.tasks.build], remote: true) do |f| %>
  <%= f.text_field :content, placeholder: "New Task", required: true %>
  <%= f.submit 'Send', data: {send: "tasks"} %>
<% end %>

app/views/tasks/_task.html.erb
<div class="row clearfix" data-task="<%= task.id %>">
  <%= template =  render :partial => 'tasks/task_inner', locals: {:project => @project, :current_user => current_user, :task => task} %>
</div>

app/views/tasks/_task_inner.html.erb
<% if task.completed? %>
  <div class="complete">
    <% if (current_user.id == project.user_id) %>
	  <%= link_to(incomplete_project_task_path(project, task.id), :remote => true) do %>
	    <i style="opacity:0.4;" class="fa fa-check"></i>
	  <% end %>
    <% end %>
  </div>
  <div class="todo_item">
    <p style="opacity: 0.4;" class="task_content"><strike><%= task.content %></strike></p>
	<div class="time_left">
	  <strike>
		<%= time_ago_in_words(task.created_at) %> ago
		</strike>
    </div>
  </div>
  <div class="trash">
	<% if (current_user.id == project.user_id) %>
	  <%= link_to project_task_path(project, task.id), method: :delete, :remote => true, data: { confirm: "Are you sure?" } do %>
	    <i class="fa fa-trash"></i>
	  <% end %>
	<% end %>	
  </div>
<% else %>
  <div class="complete">
    <% if (current_user.id == project.user_id) %>
	  <%= link_to(complete_project_task_path(project, task.id), :remote => true) do %> 
	    <i class="fa fa-check"></i>
	  <% end %>
    <% end %>
  </div>
  <div class="todo_item">
    <p class="task_content"><%= task.content %></p>
	<div class="time_left">
	  <%= time_ago_in_words(task.created_at) %> ago
	</div>
  </div>
  <div class="trash">
    <% if (current_user.id == project.user_id) %>
	  <%= link_to project_task_path(project, task.id), method: :delete, :remote => true, data: { confirm: "Are you sure?" } do %>
	    <i class="fa fa-trash"></i>
	  <% end %>
	<% end %>	
  </div>
<% end %>